# Generated by Django 5.0.6 on 2024-05-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_examcenter_remove_student_id_student_examcenter_ptr'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyExamCenterProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('school.examcenter',),
        ),
    ]
