# Generated by Django 5.0.6 on 2024-05-17 16:32

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_myexamcenterproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school.student')),
                ('page_name', models.CharField(max_length=70)),
                ('page_cat', models.CharField(max_length=70)),
                ('publish', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='myexamcenterproxy',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('students', django.db.models.manager.Manager()),
            ],
        ),
    ]
